spring:
  datasource:
    authorization:
      url: jdbc:sqlserver://127.0.0.1;encrypt=true;trustservercertificate=true;databaseName=authorization;
      jdbcurl: jdbc:sqlserver://127.0.0.1;encrypt=true;trustservercertificate=true;databaseName=authorization;
      username: sa
      password: 123456
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver